config/routes.rb
Rails.application.routes.draw do
  root to: 'home#index'

  resources :sessions, only: [:new, :create, :destroy]
  get 'login', to: 'sessions#new', as: 'login'
  get 'logout', to: 'sessions#destroy', as: 'logout'

  get 'game', to: 'game#index'

  get 'vision_board', to: 'vision_board#index'
  get 'project_management', to: 'project_management#index'

  get '/item/:id/drop', to: 'items#drop_item', as: 'drop_item'
  get '/item/:id/equip', to: 'items#equip_item', as: 'equip_item'
  get '/item/:id/use', to: 'items#use_item', as: 'use_item'
  get '/unequip_pet', to: 'items#unequip_pet', as: 'unequip_pet'
  get '/unequip_tool', to: 'items#unequip_tool', as: 'unequip_tool'
  get '/unequip_vehicle', to: 'items#unequip_vehicle', as: 'unequip_vehicle'

  get '/feed_mount/:item_id', to: 'game#feed_mount', as: 'feed_mount'
  get '/location/:id/travel', to: 'game#travel', as: 'travel'
  get '/resource/:id/gather', to: 'game#gather', as: 'gather'

  resources :locations, param: :location_id, only: [] do
    member do
      resources :chats, only: [:index, :create]
    end
  end

  # TODO: Experiment: a vanilla, RESTful, endpoint for gameplay, integrated into UI with TURBO-frames
  # Combined with turbo, this could really make sense
  # game_path renders the ui
  # the viewport could have location#show
  # dungeons:
  #   dungeon#show/index/run
  #   maybe admins can visit dungeon#edit?
  # designing an item is craft#new
  # crafting an item is item#create
  # looking at an item is item#show, rendered inside a popup with turbo
  # renaming an item is item#edit
  # dropping an item is item#destroy
  # dont have to do it this way.  Custom routes is fine.  It just might be easier to use standard rails routes
  # But maybe not.  Maybe I like custom routes better?
  # Standard routing does seem to name thing backwards.  See 'inventory_building_path'.
  #   'building_inventory_path' would be better
  #   That would have to be custom

  resources :dungeons, only: [:index, :show] do
    member do
      get 'run', to: 'dungeons#run'
    end
  end

  get 'craft/design', to: 'craft#design', as: 'craft_design'
  post 'craft/confirm', to: 'craft#confirm', as: 'craft_confirm'

  resources :buildings, param: :building_id, only: [] do
    member do
      get '/add_item/:item_id', to: 'buildings#add_item', as: 'add_item'
      get '/select_item', to: 'buildings#select_item', as: 'select_item'
      get '/pickup_item/:item_id', to: 'buildings#pickup_item', as: 'pickup_item'
      get '/inventory', to: 'buildings#inventory', as: 'inventory'

      resources :listings, except: :show do
        member do
          get '/purchase', to: 'listings#purchase'
          get '/confirm_purchase', to: 'listings#confirm_purchase'
        end
      end
    end
  end

  resources :users

  # Cheats
  get 'monster_energy', to: 'cheats#monster_energy'
end

app/controllers/game_controller.rb
class GameController < ApplicationController
  before_action :logged_in

  def index
    game_action redirect: false do
      @current_location = player.location
      @local_players    = User.where(location: @current_location).where.not(id: player.id)
      @local_resources  = Resource.where(location: @current_location)
      @local_buildings  = @current_location.property
      @local_messages   = Chat.where(location: @current_location).order(created_at: :desc).limit(25)
      @active_control   = params[:active_control] || 'actions'
    end
  end

  def feed_mount
    game_action do
      player.vehicle.feed Item.find(params[:item_id])
    end
  end

  def gather
    game_action do
      item    = player.tool.gather(Resource.find(params[:id]))
      @notice = level_color_span(item.level, item.full_name)
    end
  end

  def travel
    game_action do
      location = Location.find(params[:id])

      player.vehicle.travel(location)
    end
  end
end

app/views/game/_buildings.html.erb
<input type="radio" id="radio-buildings" name="radios" value="buildings"
       <% if @active_control == 'buildings' %>
       checked="checked"
       <% end %>
         />
<div class="section buildings">
  <label for="radio-buildings" class="radio">B</label>
  <div class="section-content">
    <h4 class="section-title">Buildings</h4>
    <ul>
      <% @local_buildings.items.each do |building| %>
        <li data-turbo="false">
          <%= level_color_span(building.level, link_to(building.name, "#building-#{ building.id }")) %>
        </li>
        <%= render partial: 'building_popup', locals: { building: } %>
      <% end %>
    </ul>
  </div>
</div>

app/views/game/_dungeon_popup.html.erb
<div id="dungeon-<%= dungeon.id %>-popup" class="popup">
  <div class="popup-content dungeon-popup">
    <%= link_to 'X', game_path(active_control: 'actions'), class: 'close-button', data: { turbo_target: '_top' } %>
    <%= turbo_frame_tag 'dungeon-details', src: dungeon do %>
      <%= render partial: 'dungeons/details', locals: { dungeon: } %>
    <% end %>
  </div>
</div>

app/views/game/_equipment.html.erb
<input type="radio" id="radio-equipment" name="radios" value="equipment"
       <% if @active_control == 'equipment' %>
       checked="checked"
       <% end %>
         />
<div class="section equipment">
  <label for="radio-equipment" class="radio">E</label>
  <div class="section-content">
    <h4 class="section-title">Equipment</h4>
    <table>
      <tr>
        <td>Tool:</td>
        <td>
          <% if player.tool %>
            <%= level_color_span(player.tool.level, player.tool.full_name) %>
          <% end %>
        </td>
        <td>
          <% if player.tool %>
            <%= link_to 'X', unequip_tool_path, id: 'unequip_tool' %>
          <% end %>
        </td>
      </tr>
      <tr>
        <td>Vehicle:</td>
        <td>
          <% if player.vehicle %>
            <%= level_color_span(player.vehicle.level, player.vehicle.full_name) %>
            <% if player.vehicle.boosted? %>
              <span>(Happy)</span>
            <% end %>
          <% end %>
        </td>
        <td>
          <% if player.vehicle %>
            <%= link_to 'X', unequip_vehicle_path, id: 'unequip_vehicle' %>
          <% end %>
        </td>
      </tr>
      <tr>
        <td>Instrument:</td>
        <td></td>
      </tr>
      <tr>
        <td>Clothes:</td>
        <td></td>
      </tr>
      <tr>
        <td>Pet:</td>
        <td>
          <% if player.pet %>
            <%= level_color_span(player.pet.level, player.pet.full_name) %>
          <% end %>
        </td>
        <td>
          <% if player.pet %>
            <%= link_to 'X', unequip_pet_path, id: 'unequip_pet' %>
          <% end %>
        </td>
      </tr>
    </table>
  </div>
</div>

app/views/game/_feed_popup.html.erb
<div id="feed">
  <h3>Choose a food</h3>
  <ul>
  <% player.vehicle.feedable_items.each do |item| %>
    <li class="<%= level_name item.level %>">
      <%= link_to item.full_name, feed_mount_path(item) %>
    </li>
  <% end %>
  </ul>
</div>

app/views/game/_game_menu.html.erb
<div class="game-menu">
  <a href="#game-menu-popup" id="game-menu-button" class="button" data-turbo="false">
    <span>...</span>
    <span>...</span>
    <span>...</span>
  </a>
  <div id="game-menu-popup" class="popup">
    <div class="popup-content game-menu-popup">
      <%= link_to 'X', game_path, class: 'close-button', data: { turbo_target: '_top' } %>
      <h4 class="title">Game Menu</h4>
      <span class="version">Version 0.3</span><span>build_<%= ENV['HEROKU_RELEASE_VERSION'] %></span>
      <ul class="links">
        <% if player -%>
          <li><%= link_to 'Settings', edit_user_path(player) %></li>
          <li><%= link_to 'Upcoming Changes', project_management_path %></li>
          <li><%= link_to 'Vision Board', vision_board_path %></li>
          <li><%= link_to 'Log Out', logout_path %></li>
        <% end %>
      </ul>
    </div>
  </div>
</div>

app/views/game/_inventory.html.erb
<input type="radio" id="radio-inventory" name="radios" value="inventory"
       <% if @active_control == 'inventory' %>
       checked="checked"
       <% end %>
         />
<div class="section inventory">
  <label for="radio-inventory" class="radio">I</label>
  <div class="section-content">
    <h4 class="section-title">Inventory</h4>
    <span class="remaining-space"><%= player.child_inventory.remaining_space %></span>
    <ul class="player-inventory">
      <li class="credits">Credits: <%= player.credits %><%= credit_symbol %></li>
      <%= render partial: 'item_list', locals: { inventory: player.child_inventory } %>
    </ul>
    <% if player&.pet&.child_inventory %>
      <div class="pet-inventory">
        <span class="remaining-space"><%= player.pet.child_inventory.remaining_space %></span>
        <h4>
          <span class="<%= level_name player.pet.level %>"><%= player.pet.full_name %> </span>
          Inventory</h4>
        <ul>
          <%= render partial: 'item_list', locals: { inventory: player.pet.child_inventory } %>
        </ul>
      </div>
    <% end %>
    <% if player&.vehicle&.child_inventory %>
      <div class="vehicle-inventory">
        <span class="remaining-space"><%= player.vehicle.child_inventory.remaining_space %></span>
        <h4>
          <span class="<%= level_name player.vehicle.level %>"><%= player.vehicle.full_name %> </span>
          Inventory</h4>
        <ul>
          <%= render partial: 'item_list', locals: { inventory: player.vehicle.child_inventory } %>
        </ul>
      </div>
    <% end %>
  </div>
</div>

app/views/game/_inventory_fieldset.html.erb
<fieldset class="inventory">
  <legend>Inventory</legend>
  <ul>
    <% @current_user.inventory.items.each do |item| %>
      <li><%= link_to item.name, "#item-#{ item.id }-details" %></li>
      <%= render partial: 'inventory_popup', locals: { item: } %>
    <% end %>
  </ul>
</fieldset>

app/views/game/_inventory_popup.html.erb
<div id="item-<%= item.id %>-details" class="popup">
  <div class="popup-content">
    <a href="#" class="close">X</a>
    <h4 class="name"><%= item.name %></h4>
    <% if item.equipable? %>
      <%= link_to 'Equip', equip_item_path(item) %>
    <% end %>
    <span class="level"><%= item.level_name %></span>
    <span class="created-by">Created by <%= item.created_by.name %></span>
    <p class="description"><%= item.description %></p>
  </div>
</div>

app/views/game/_lifeforms.html.erb
<input type="radio" id="radio-lifeforms" name="radios" value="lifeforms"
       <% if @active_control == 'lifeforms' %>
       checked="checked"
       <% end %>
         />
<div class="section lifeforms">
  <label for="radio-lifeforms" class="radio">L</label>
  <div class="section-content">
    <h4 class="section-title">Lifeforms</h4>
    <% if @local_players.any? %>
      <span>Local Players:</span>
      <ul>
        <% @local_players.each do |player| %>
          <li data-turbo="false"><%= link_to player.name, "#player-#{ player.id }-details" %></li>
          <%= render partial: 'player_popup', locals: { player: } %>
        <% end %>
      </ul>
    <% end %>
  </div>
</div>

app/views/game/_location.html.erb
<span class="title">
    <span class="name" style="
    color: <%= @current_location.bg_color %>;
      <% if @current_location.highlight_color %>
      text-shadow: 0 0 4px <%= @current_location.highlight_color %>;
      <% end %>
    ">
      <%= @current_location.name %>
    </span>
    <span class="type">
      &lt;<%= @current_location.type %>&gt;
    </span>
  </span>
<p class="description"><%= @current_location.description %></p>
<div class="viewport"
     style="
     background-image: linear-gradient(to top, <%= @current_location.bg_color %>, #668cff);
       /*'#668cff'*/
     ">
  <% if @current_location.type == 'Wilderness' %>
    <%= image_tag 'earth_clear.png', class: 'background' %>
  <% else %>
    <%= image_tag 'house.png', class: 'background' %>
  <% end %>
</div>

app/views/game/_player_popup.html.erb
<div id="player-<%= player.id %>-details" class="popup">
  <div class="popup-content player-popup">
    <%= link_to 'X', game_path(active_control: 'lifeforms'), class: 'close-button', data: { turbo_target: '_top' } %>
    <h4 class="title"><%= player.name %></h4>
    <table>

      <tr class="status">
        <td>Status:</td>
        <td class="status status-<%= player.status.downcase %>">
          <%= player.status %>
        </td>
      </tr>
      <% if player.tool %>
        <tr class="equipment">
          <td class="tool">Tool:</td>
          <td><%= level_color_span(player.tool.level, player.tool.name) %></td>
        </tr>
      <% end %>
      <% if player.vehicle %>
        <tr class="equipment">
          <td class="vehicle">Vehicle:</td>
          <td><%= level_color_span(player.vehicle.level, player.vehicle.name) %></td>
        </tr>
      <% end %>
      <% if player.pet %>
        <tr class="equipment">
          <td class="pet">Pet:</td>
          <td><%= level_color_span(player.pet.level, player.pet.name) %></td>
        </tr>
      <% end %>
      </tr>
    </table>
  </div>
</div>

app/views/game/_recipes_popup.html.erb
<fieldset id="recipes">
  <legend><%= player.tool.name %> Recipes</legend>
  <table>
    <thead>
    <tr>
      <th>Item</th>
      <th>Recipe</th>
    </tr>
    </thead>
    <% player.tool.recipes.each do |recipe| %>
      <tr>
        <td>
          <%= recipe[:item].crafting_yield if recipe[:item].crafting_yield > 1 %>
          <%= recipe[:item].pretty_type %>
        </td>
        <td>
          <% recipe[:recipe].each do |ingredient, amount| %>
          <span>
            <%= amount %>x
            <%= pretty_type(ingredient) %>
          </span>
          <% end %>
        </td>
      </tr>
    <% end %>
  </table>
</fieldset>

app/views/game/_skills.html.erb
<input type="radio" id="radio-skills" name="radios" value="skills"
       <% if @active_control == 'skills' %>
       checked="checked"
       <% end %>
         />
<div class="section skills">
  <label for="radio-skills" class="radio">S</label>
  <div class="section-content">
    <h4 class="section-title">Skills</h4>
    <table>
      <tr>
        <td><%= Skills::CRAFTING %>:</td>
        <td>
          <%= @player.skills.crafting %>
        </td>
      </tr>
      <tr>
        <td><%= Skills::FIGHTING %>:</td>
        <td>
          <%= @player.skills.fighting %>
        </td>
      </tr>
      <tr>
        <td><%= Skills::GATHERING %>:</td>
        <td>
          <%= @player.skills.gathering %>
        </td>
      </tr>
      <tr>
        <td><%= Skills::TRADING %>:</td>
        <td>
          <%= @player.skills.trading %>
        </td>
      </tr>
      <tr>
        <td><%= Skills::TRAVELING %>:</td>
        <td>
          <%= @player.skills.traveling %>
        </td>
      </tr>
    </table>
  </div>
</div>

app/views/game/_travel_popup.html.erb
<% if player.vehicle.boosted? %>
  <p>Happy Mount Bonus!</p>
<% end %>
<table class="locations">
  <thead>
  <tr>
    <th>Location</th>
    <th>Distance</th>
    <th>Energy</th>
  </tr>
  </thead>
  <% player.vehicle.valid_travel_locations.each do |location| %>
    <tr>
      <td><%= link_to location.name, travel_path(location) %></td>
      <td><%= @current_location.distance_from(location) %> km</td>
      <td><%= player.vehicle.energy_usage(@current_location, location) %> <%= credit_symbol %></td>
    </tr>
  <% end %>
</table>