config/routes.rb
Rails.application.routes.draw do
  root to: 'home#index'

  resources :sessions, only: [:new, :create, :destroy]
  get 'login', to: 'sessions#new', as: 'login'
  get 'logout', to: 'sessions#destroy', as: 'logout'

  get 'game', to: 'game#index'

  get 'vision_board', to: 'vision_board#index'
  get 'project_management', to: 'project_management#index'

  get '/item/:id/drop', to: 'items#drop_item', as: 'drop_item'
  get '/item/:id/equip', to: 'items#equip_item', as: 'equip_item'
  get '/item/:id/use', to: 'items#use_item', as: 'use_item'
  get '/unequip_pet', to: 'items#unequip_pet', as: 'unequip_pet'
  get '/unequip_tool', to: 'items#unequip_tool', as: 'unequip_tool'
  get '/unequip_vehicle', to: 'items#unequip_vehicle', as: 'unequip_vehicle'

  get '/feed_mount/:item_id', to: 'game#feed_mount', as: 'feed_mount'
  get '/location/:id/travel', to: 'game#travel', as: 'travel'
  get '/resource/:id/gather', to: 'game#gather', as: 'gather'

  resources :locations, param: :location_id, only: [] do
    member do
      resources :chats, only: [:index, :create]
    end
  end

  # TODO: Experiment: a vanilla, RESTful, endpoint for gameplay, integrated into UI with TURBO-frames
  # Combined with turbo, this could really make sense
  # game_path renders the ui
  # the viewport could have location#show
  # dungeons:
  #   dungeon#show/index/run
  #   maybe admins can visit dungeon#edit?
  # designing an item is craft#new
  # crafting an item is item#create
  # looking at an item is item#show, rendered inside a popup with turbo
  # renaming an item is item#edit
  # dropping an item is item#destroy
  # dont have to do it this way.  Custom routes is fine.  It just might be easier to use standard rails routes
  # But maybe not.  Maybe I like custom routes better?
  # Standard routing does seem to name thing backwards.  See 'inventory_building_path'.
  #   'building_inventory_path' would be better
  #   That would have to be custom

  resources :dungeons, only: [:index, :show] do
    member do
      get 'run', to: 'dungeons#run'
    end
  end

  get 'craft/design', to: 'craft#design', as: 'craft_design'
  post 'craft/confirm', to: 'craft#confirm', as: 'craft_confirm'

  resources :buildings, param: :building_id, only: [] do
    member do
      get '/add_item/:item_id', to: 'buildings#add_item', as: 'add_item'
      get '/select_item', to: 'buildings#select_item', as: 'select_item'
      get '/pickup_item/:item_id', to: 'buildings#pickup_item', as: 'pickup_item'
      get '/inventory', to: 'buildings#inventory', as: 'inventory'

      resources :listings, except: :show do
        member do
          get '/purchase', to: 'listings#purchase'
          get '/confirm_purchase', to: 'listings#confirm_purchase'
        end
      end
    end
  end

  resources :users

  # Cheats
  get 'monster_energy', to: 'cheats#monster_energy'
end

app/models/listing.rb
class Listing < ApplicationRecord
  belongs_to :building, class_name: 'Item::Crafted::Building'
  belongs_to :created_by, class_name: 'User'
  belongs_to :item

  def purchase(buyer)
    raise CraftyError, 'You can\'t afford that.' unless can_afford?(buyer)

    buyer.update(credits: (buyer.credits - price))

    if infinite
      new_item                  = item.dup
      new_item.parent_inventory = buyer.child_inventory
      new_item.save
    else
      created_by.update(credits: (created_by.credits + price))
      item.update(parent_inventory: buyer.child_inventory)
      destroy
    end
  end

  private

  def can_afford?(buyer)
    price <= buyer.credits
  end
end

app/controllers/listings_controller.rb
class ListingsController < ApplicationController
  before_action :logged_in
  before_action :set_listing, except: [:index, :new, :create]
  before_action :set_building

  def index
    game_action redirect: false do
      @listings = Listing.all
    end
  end

  def new
    game_action redirect: false do
      @listing     = Listing.new
      @valid_items = player.carried_items + @building.child_inventory.items - building_listing_items
    end
  end

  def edit; end

  def create
    game_action path: listings_path(@building) do
      @listing = Listing.new(listing_params)

      @listing.item.update(parent_inventory: nil) if @listing.save
    end
  end

  def update
    game_action path: listings_path(@building) do
      if @listing.update(listing_params)
        item                     = @listing.item
        item.parent_inventory_id = @building.child_inventory_id
        item.save
      end
    end
  end

  def destroy
    game_action path: listings_path(@building) do
      @listing.destroy!
    end
  end

  def purchase; end

  def confirm_purchase
    game_action path: listings_path(@building) do
      @listing.purchase(player)
    end
  end

  private

  def set_listing
    @listing = Listing.find(params.expect(:id))
  end

  def set_building
    @building = Item::Crafted::Building.find(params.expect(:building_id))
  end

  def building_listing_items
    @building.listings.map(&:item)
  end

  def listing_params
    params.expect(listing: [:building_id, :item_id, :created_by_id, :price])
  end
end

app/helpers/listings_helper.rb
module ListingsHelper
end

app/views/listings/_form.html.erb
<%= form_with(model: listing) do |form| %>
  <% if listing.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(listing.errors.count, "error") %> prohibited this listing from being saved:</h2>

      <ul>
        <% listing.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.hidden_field :building_id, value: params[:building_id] %>
  </div>

  <div>
    <%= form.label :item_id %>
    <%= form.collection_select :item_id, @valid_items, :id, :full_name_level %>
  </div>

  <div>
    <%= form.hidden_field :created_by_id, value: player.id %>
  </div>

  <div>
    <%= form.label :price, "Credits#{credit_symbol}" %>
    <%= form.number_field :price %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/listings/edit.html.erb
<% content_for :title, "Editing listing" %>

<h1>Editing listing</h1>

<%= render "form", listing: @listing %>

<br>

<div>
  <%= link_to "Show this listing", @listing %> |
  <%= link_to "Back to listings", listings_path %>
</div>

app/views/listings/index.html.erb
<%= turbo_frame_tag 'building-sales-listing' do %>
  <%= render partial: 'buildings/building_sales_listing', locals: { building: @building } %>
<% end %>

app/views/listings/new.html.erb
<% content_for :title, "New listing" %>

<%= turbo_frame_tag 'building-sales-listing' do %>
  <h1>New listing</h1>

  <%= render "form", listing: @listing %>

  <%= link_to 'Cancel', listings_path(@building)  %>
<% end %>
<br>

<div>
  <%= link_to "Back to listings", listings_path %>
</div>

app/views/listings/purchase.html.erb
<%= turbo_frame_tag 'building-sales-listing' do %>
  <p>
    Really purchase <%= @listing.item.stack_amount %>x <%= @listing.item.full_name %>
    for <%= @listing.price %><%= credit_symbol %>?
  </p>

  <%= link_to "Pay #{@listing.price}#{credit_symbol}", confirm_purchase_listing_path(@building, @listing) %>
  <%= link_to 'Cancel', listings_path(@building) %>
<% end %>