config/routes.rb
Rails.application.routes.draw do
  root to: 'home#index'

  resources :sessions, only: [:new, :create, :destroy]
  get 'login', to: 'sessions#new', as: 'login'
  get 'logout', to: 'sessions#destroy', as: 'logout'

  get 'game', to: 'game#index'

  get 'vision_board', to: 'vision_board#index'
  get 'project_management', to: 'project_management#index'

  get '/item/:id/drop', to: 'items#drop_item', as: 'drop_item'
  get '/item/:id/equip', to: 'items#equip_item', as: 'equip_item'
  get '/item/:id/use', to: 'items#use_item', as: 'use_item'
  get '/unequip_pet', to: 'items#unequip_pet', as: 'unequip_pet'
  get '/unequip_tool', to: 'items#unequip_tool', as: 'unequip_tool'
  get '/unequip_vehicle', to: 'items#unequip_vehicle', as: 'unequip_vehicle'

  get '/feed_mount/:item_id', to: 'game#feed_mount', as: 'feed_mount'
  get '/location/:id/travel', to: 'game#travel', as: 'travel'
  get '/resource/:id/gather', to: 'game#gather', as: 'gather'

  resources :locations, param: :location_id, only: [] do
    member do
      resources :chats, only: [:index, :create]
    end
  end

  # TODO: Experiment: a vanilla, RESTful, endpoint for gameplay, integrated into UI with TURBO-frames
  # Combined with turbo, this could really make sense
  # game_path renders the ui
  # the viewport could have location#show
  # dungeons:
  #   dungeon#show/index/run
  #   maybe admins can visit dungeon#edit?
  # designing an item is craft#new
  # crafting an item is item#create
  # looking at an item is item#show, rendered inside a popup with turbo
  # renaming an item is item#edit
  # dropping an item is item#destroy
  # dont have to do it this way.  Custom routes is fine.  It just might be easier to use standard rails routes
  # But maybe not.  Maybe I like custom routes better?
  # Standard routing does seem to name thing backwards.  See 'inventory_building_path'.
  #   'building_inventory_path' would be better
  #   That would have to be custom

  resources :dungeons, only: [:index, :show] do
    member do
      get 'run', to: 'dungeons#run'
    end
  end

  get 'craft/design', to: 'craft#design', as: 'craft_design'
  post 'craft/confirm', to: 'craft#confirm', as: 'craft_confirm'

  resources :buildings, param: :building_id, only: [] do
    member do
      get '/add_item/:item_id', to: 'buildings#add_item', as: 'add_item'
      get '/select_item', to: 'buildings#select_item', as: 'select_item'
      get '/pickup_item/:item_id', to: 'buildings#pickup_item', as: 'pickup_item'
      get '/inventory', to: 'buildings#inventory', as: 'inventory'

      resources :listings, except: :show do
        member do
          get '/purchase', to: 'listings#purchase'
          get '/confirm_purchase', to: 'listings#confirm_purchase'
        end
      end
    end
  end

  resources :users

  # Cheats
  get 'monster_energy', to: 'cheats#monster_energy'
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    redirect_to game_path unless player.nil?
  end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/index.html.erb
<h1>Crafty</h1>
<h2>aka "Loom 40K"</h2>
<%= link_to 'Log In', login_path %>
<p>Welcome!</p>
<p>
  Crafty is just the working title for our game.  It is a MMO roguelike point and click adventure game.
  Our goal is a modern MUD-style game with some interesting twists.
</p>
<p>
  That's a lot of buzzwords!  In other terms, it is a muiltiplayer adventure game. Like the old LucasArts games.
  But there are also other players wandering around.
</p>
<p>
  There are a few activities to do in game: gathering, crafting, exploring, trading, and you'll find more, too.
  There are even player-created quests, as well as world quests that lead the plot of the game forward.
</p>
<p>
  No one can live forever, though.  Whether pirates get you, or simple old age, eventually your character will die.
  Very sad, but c'est la vie!  Its ok, you can will your items to your offspring/adopted kid/clone.
  You get to continue the adventure, maybe with bonuses depending on how well you did in the last life.
</p>
<p>
  If you have any questions, send an email to <a href='mailto:kentslaymaker@gmail.com'>KentSlaymaker@gmail.com</a>
</p>
<p>
  This game is in pre-alpha. Your user will be reset all the time, with no warning. But your account won't be deleted.
</p>