config/routes.rb
Rails.application.routes.draw do
  root to: 'home#index'

  resources :sessions, only: [:new, :create, :destroy]
  get 'login', to: 'sessions#new', as: 'login'
  get 'logout', to: 'sessions#destroy', as: 'logout'

  get 'game', to: 'game#index'

  get 'vision_board', to: 'vision_board#index'
  get 'project_management', to: 'project_management#index'

  get '/item/:id/drop', to: 'items#drop_item', as: 'drop_item'
  get '/item/:id/equip', to: 'items#equip_item', as: 'equip_item'
  get '/item/:id/use', to: 'items#use_item', as: 'use_item'
  get '/unequip_pet', to: 'items#unequip_pet', as: 'unequip_pet'
  get '/unequip_tool', to: 'items#unequip_tool', as: 'unequip_tool'
  get '/unequip_vehicle', to: 'items#unequip_vehicle', as: 'unequip_vehicle'

  get '/feed_mount/:item_id', to: 'game#feed_mount', as: 'feed_mount'
  get '/location/:id/travel', to: 'game#travel', as: 'travel'
  get '/resource/:id/gather', to: 'game#gather', as: 'gather'

  resources :locations, param: :location_id, only: [] do
    member do
      resources :chats, only: [:index, :create]
    end
  end

  # TODO: Experiment: a vanilla, RESTful, endpoint for gameplay, integrated into UI with TURBO-frames
  # Combined with turbo, this could really make sense
  # game_path renders the ui
  # the viewport could have location#show
  # dungeons:
  #   dungeon#show/index/run
  #   maybe admins can visit dungeon#edit?
  # designing an item is craft#new
  # crafting an item is item#create
  # looking at an item is item#show, rendered inside a popup with turbo
  # renaming an item is item#edit
  # dropping an item is item#destroy
  # dont have to do it this way.  Custom routes is fine.  It just might be easier to use standard rails routes
  # But maybe not.  Maybe I like custom routes better?
  # Standard routing does seem to name thing backwards.  See 'inventory_building_path'.
  #   'building_inventory_path' would be better
  #   That would have to be custom

  resources :dungeons, only: [:index, :show] do
    member do
      get 'run', to: 'dungeons#run'
    end
  end

  get 'craft/design', to: 'craft#design', as: 'craft_design'
  post 'craft/confirm', to: 'craft#confirm', as: 'craft_confirm'

  resources :buildings, param: :building_id, only: [] do
    member do
      get '/add_item/:item_id', to: 'buildings#add_item', as: 'add_item'
      get '/select_item', to: 'buildings#select_item', as: 'select_item'
      get '/pickup_item/:item_id', to: 'buildings#pickup_item', as: 'pickup_item'
      get '/inventory', to: 'buildings#inventory', as: 'inventory'

      resources :listings, except: :show do
        member do
          get '/purchase', to: 'listings#purchase'
          get '/confirm_purchase', to: 'listings#confirm_purchase'
        end
      end
    end
  end

  resources :users

  # Cheats
  get 'monster_energy', to: 'cheats#monster_energy'
end

app/models/item/craftable/building.rb
class Item::Craftable::Building < Item
  include Makeable

  before_create :provision_inventory

  has_many :listings

  DEFAULT_INVENTORY_SIZE = 50

  private

  def provision_inventory
    create_child_inventory(size: DEFAULT_INVENTORY_SIZE)
  end
end

app/models/item/crafted/building.rb
class Item::Crafted::Building < Item::Crafted
  include Useable

  before_create :provision_inventory

  has_many :listings

  DEFAULT_INVENTORY_SIZE = 50

  def recipe
    {
      ItemType::CRAFTED[:plank] => 10,
      ItemType::CRAFTED[:beam] => 3,
      ItemType::CRAFTED[:screw] => 400
    }
  end

  def use
    location = parent_inventory.user.location
    parent_inventory.remove_item(self)
    location.property.add_item(self)
  end

  private

  def provision_inventory
    create_child_inventory(size: DEFAULT_INVENTORY_SIZE)
  end
end

app/controllers/buildings_controller.rb
class BuildingsController < ApplicationController
  before_action :logged_in
  before_action :set_building
  before_action :set_item, only: [:add_item, :pickup_item]

  def add_item
    game_action(path: inventory_building_path(@building)) do
      @player.remove_item(@item)
      @building.child_inventory.add_item(@item)
    end
  end

  def inventory; end

  def pickup_item
    game_action(path: inventory_building_path(@building)) do
      @building.child_inventory.remove_item(@item)
      @player.add_item(@item)
    end
  end

  def sales_listings; end

  def select_item; end

  private

  def set_item
    @item = Item.find(params[:item_id])
  end

  def set_building
    @building = Item::Crafted::Building.find(params[:building_id])
  end
end

app/views/buildings/_building_inventory.html.erb
<% if building.permitted_user?(player) %>
  <%= link_to('Add Item', select_item_building_path(building)) %>
<% else %>
  <span>Private Building</span>
<% end %>
<ul>
  <% building.child_inventory.items.each do |item| %>
    <li>
      <%= item.stack_amount %>x
      <%= level_color_span(item.level, item.full_name) %>
      <% if building.permitted_user?(player) %>
        <%= link_to 'pickup', pickup_item_building_path(building, item), id: "pickup-#{item.id}" %>
      <% end %>
    </li>
  <% end %>
</ul>

app/views/buildings/_building_sales_listing.html.erb
<% if building.permitted_user?(player) %>
  <%= link_to('List Sale', new_listing_path(building)) %>
<% else %>
  <span>Private Building</span>
<% end %>
<table>
  <thead>
  <tr>
    <th>Listed By</th>
    <th>Item for Sale</th>
    <th>Price</th>
  </tr>
  </thead>
  <% building.listings.each do |listing| %>
    <tr>
      <td><%= listing.created_by.name %></td>
      <td>
        <%= listing.item.stack_amount %>x
        <span class="<%= level_name(listing.item.level) %>">
          <%= link_to listing.item.full_name, purchase_listing_path(building, listing) %>
        </span>
      <td>
        <%= listing.price %><%= credit_symbol %>
      </td>
    </tr>
  <% end %>
</table>

app/views/buildings/inventory.html.erb
<%= turbo_frame_tag 'building-inventory' do %>
  <%= render partial: 'building_inventory', locals: { building: @building } %>
<% end %>

app/views/buildings/sales_listings.html.erb
<%= turbo_frame_tag 'building-sales-listing' do %>
  <%= render partial: 'building_sales_listing', locals: { building: @building } %>
<% end %>

app/views/buildings/select_item.html.erb
<%= turbo_frame_tag 'building-inventory' do %>
  <%= link_to 'Cancel', inventory_building_path(@building) %>
  <ul>
    <% player.carried_items.each do |item| %>
      <li>
        <%= item.stack_amount %>x
        <%= level_color_span(item.level, link_to(item.full_name, add_item_building_path(@building, item))) %>
      </li>
    <% end %>
  </ul>
<% end %>